### ISSUE TITLE
Black screen again 

### ISSUE THREAD

**Issue by Nonor35** [z4roc/valstore-mobile#15]
That directly after the login
![Screenshot_2024-09-24-16-05-28-63_86d659f69971452ae5c2d44ff4624ec6](https://github.com/user-attachments/assets/1118537e-d624-4f96-8591-8ba373a9627b)
My friend have this issue too so i don't think my phone is the issue

**Comment by z4roc** [comment]
yeah this started happening from today on. they changed the storefront endpoint so there is no data available, docs arent updated yet so we dont know how you have to retrieve the store data from now on.

**Comment by z4roc** [comment]
Looks like the storefront v2 endpoint got disabled and deprecated by Riot Games, check out the latest release where I migrated to the v3 endpoint, everything should be good to go now!
