### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by Dojima1489** [z4roc/valstore-mobile#19]
It might be because Riot update client and Valstore is on black screen now.

**Comment by yelvea** [comment]
experiencing the same

**Comment by Losamor13** [comment]
Same problem

**Comment by LoanLenoir** [comment]
So what is the solution ?

**Comment by 0ember1** [comment]
Same problem, but @z4roc hasn't posted any updates for the last 2 days
![image](https://github.com/user-attachments/assets/f5c75961-d943-487a-87cf-7f241959b104)

**Comment by Losamor13** [comment]
I think he knows that problem, probably he is fixing it


чт, 21 нояб. 2024 г., 09:53 0ember1 ***@***.***>:

**Comment by z4roc** [comment]
Yup im onto it riot indeed messed with the api again, this time I unfortunately have to do some more work, also I'm migrating to a newer flutter version and with that different packages, can't tell if im done today

**Comment by yelvea** [comment]
thanks for the updates :) appreciate your work

**Comment by z4roc** [comment]
So as far as now I finally managed to push the new stuff, migrating took ages, since the project was still based of a flutter version of 2 years ago, but with the latest release, everything should work now. https://github.com/z4roc/valstore-mobile/releases/tag/valstore_2_1_0
