### ISSUE TITLE
Black screen wasnt fixed

### ISSUE THREAD

**Issue by root-omp** [z4roc/valstore-mobile#20]
Still have black screen, even though i have updated to v2.1
![Screenshot_2024-11-22-02-13-03-79_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/4fb86d1e-ad8f-4eae-976a-54ee84069d3f)
![Screenshot_2024-11-22-02-12-44-86_86d659f69971452ae5c2d44ff4624ec6](https://github.com/user-attachments/assets/e4fbdaca-6458-4066-882d-f1274732c3ee)

**Comment by VelikiySebas** [comment]
same

**Comment by yelvea** [comment]
yeah the black screen is back

**Comment by z4roc** [comment]
Please check out the latest release and tell me if it works for yall
