### ISSUE TITLE
Blank screen on valstore again

### ISSUE THREAD

**Issue by S-9907** [z4roc/valstore-mobile#21]
Hi the app is down for me again I uninstalled and reinstalled but same issue
![Screenshot_20241121_235305](https://github.com/user-attachments/assets/790f3870-bdf5-4c73-af85-3a96ef005bc9)

**Comment by z4roc** [comment]
As #20 please check out the latest release 2.1.1

**Comment by S-9907** [comment]
Yes it works now thank you
